export type IconType =
  | "social-vk"
  | "social-tg"
  | "social-ok"
  | "star-filled"
  | "close"
  | "chevron-right"
  | "social-youtube"
  | "phone"
  | "search"
  | "cart"
  | "password-hide"
  | "password-show"
  | "favorite"
  | "check"
  | "block"
  | "favorite-outlined";
